name: percobaan_4
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dropdown_search: ^2.0.1
  image_picker: ^0.8.8
  flutter_svg: ^1.0.0
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.2.0
  carousel_slider: ^4.0.0
  provider: ^6.0.5
  path_provider: ^2.0.15
  http: ^0.13.4
  shared_preferences: ^2.1.2
  flutter_bloc: ^8.1.3
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: Outfit
      fonts:
        - asset: asset/font/Outfit-Black.ttf
          weight: 900
        - asset: asset/font/Outfit-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Outfit-Bold.ttf
          weight: 700
        - asset: asset/font/Outfit-SemiBold.ttf
          weight: 600
        - asset: asset/font/Outfit-Regular.ttf
          weight: 500
        - asset: asset/font/Outfit-Medium.ttf
          weight: 400
        - asset: asset/font/Outfit-Thin.ttf
          weight: 300
        - asset: asset/font/Outfit-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Outfit-Light.ttf
          weight: 100

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
